name: Examples CI

on:
  push:
    branches:
      - "master"
      - "staging"
      - "trying"
  pull_request:

jobs:
  examples_build_and_test:
    strategy:
      matrix:
        example:
          [
            web-chat,
            eth-pm,
            eth-pm-wallet-encryption,
            relay-reactjs-chat,
            store-reactjs-chat,
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install ${{ matrix.example }}
        uses: bahmutov/npm-install@v1
        with:
          working-directory: examples/${{ matrix.example }}

      - name: Test ${{ matrix.example }}
        run: npm run test
        working-directory: examples/${{ matrix.example }}

      - name: (npm) ${{ matrix.example }} install using npm i
        if: steps.use-yarn.outputs.lockfile != 'yarn.lock'
        run: npm install
        working-directory: examples/${{ matrix.example }}

  angular_example_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install relay-angular-chat
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
          working-directory: examples/relay-angular-chat

      - name: Build relay-angular-chat
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
          working-directory: examples/relay-angular-chat

      - name: Test relay-angular-chat
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test-ci
          working-directory: examples/relay-angular-chat
