name: Examples CI

on:
  push:
    branches:
      - 'master'
      - 'staging'
      - 'trying'
  pull_request:

jobs:
  examples_build_and_test:
    strategy:
      matrix:
        example: [ web-chat, eth-pm, eth-pm-wallet-encryption, relay-reactjs-chat, store-reactjs-chat, relay-angular-chat ]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install ${{ matrix.example }}
        uses: bahmutov/npm-install@v1
        with:
          working-directory: examples/${{ matrix.example }}

      - name: Test ${{ matrix.example }}
        run: npm run test
        working-directory: examples/${{ matrix.example }}
